language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
  fi

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)

    if [[ "$TRAVIS_RUST_VERSION" == "" ]]; then
      # Build a tag
      # This prints the version number
      export version=$(grep -E "version = \"([0-9]+\.[0-9]+.[0-9]+)\"" Cargo.toml | grep -Eo -m 1 "[0-9]+\.[0-9]+.[0-9]+")
      export line_number=$(grep -En "version = \"([0-9]+\.[0-9]+.[0-9]+)\"" Cargo.toml | grep -Eo -m 1 "[0-9]+" | head -n 1)
      sed -i "${line_number}s/.*/version = \"${version}-build-${TRAVIS_BUILD_NUMBER}\"/" Cargo.toml 
      git tag -a -m "${version}-build-${TRAVIS_BUILD_NUMBER}"
      git push --tags
    fi
  fi